{"name": "test_add_exception[get_add_exception_data0]", "status": "passed", "parameters": [{"name": "get_add_exception_data", "value": "[1, 'a', 'TypeError', 'unsupported operand type(s) for +']"}], "start": 1618301941520, "stop": 1618301941520, "uuid": "ea2733b9-aefa-43d9-9528-4afe37427b66", "historyId": "6e7182f8263b22f41181629aa9c0a080", "testCaseId": "dea16635690b21d5360909ec8c6ab62c", "fullName": "homework_test.test_2th_work.TestCalculator#test_add_exception", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "计算器加法异常场景用例"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_function')"}, {"name": "tag", "value": "run(order=6)"}, {"name": "parentSuite", "value": "homework_test"}, {"name": "suite", "value": "test_2th_work"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "ShimmerShiningHoon"}, {"name": "thread", "value": "11432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework_test.test_2th_work"}]}